### ISSUE TITLE
anyway to determine a suggestion on how much to rotate an image?

### ISSUE THREAD

**Issue by joefromct** [jarun/imgd#5]
This is great, I'll be trying it out on a few current projects. 

If i have a scanned image of English characters (A form of some sort) I'd like to use this to pre-process and re-align the page.  This will give Apache Tika/Tesseract a better chance at high quality OCR.

Do you have any tips on how i can programmatically "guess" at the right % of rotation required?  

Any tips appreciated.

**Comment by ananyajana** [comment]
Hi @joefromct ,

Let me read about Apache Tika/Tesseract to have a better understanding of the use case mentioned by you. It looks like u want the program to use some sort of data mining and its prior knowledge about the letter 'A' to predict the rotation. Correct me if I am wrong.

**Comment by jarun** [comment]
Closing this as out of scope. `imgd` was never written with image recognition capabilities in mind. However, if there are contributors willing to add those features, I'll accept.
