### ISSUE TITLE
Upload imgd to pypi

### ISSUE THREAD

**Issue by reorx** [jarun/imgd#7]
First of all, thanks for making such an convenient tool for image processing. I noticed that imgd is not on pypi yet, why not making it so? Thus people could using `pip install imgd` to install it directly.

If you approve this, I can send a pull request of the essential code to register imgd to pypi.

**Comment by jarun** [comment]
Thank you! By all means. Please proceed.

**Comment by jarun** [comment]
I am assuming here that you'll be maintaining the downstream package.

**Comment by reorx** [comment]
Here, I have submit the pull request: https://github.com/jarun/imgd/pull/8 , it includes the instructions to upload the package.

> I am assuming here that you'll be maintaining the downstream package.

If you what you mean by `downstream package` is the pypi package, I think I'm OK to do so, but only with your permission. Because if I upload the package with my pypi account, the package will be binded with me, and each time the package needs to be updated, it will only be accessible through my account.

**Comment by jarun** [comment]
> and each time the package needs to be updated, it will only be accessible through my account.

Doesn't it work like Homebrew where anyone can publish updates to a package? I am not familiar with pypi.

**Comment by reorx** [comment]
No, it doesn't, pypi works in a mode that every package has a maintainer, who is the only one taj can update new version and manage it through pypi account, that's why I said I could help maintain this package, but only with your permission, because if I run `python setup.py register` now, the name `imgd` will be occupied by me, no others could ever use this name on pypi (unless the administers found this package abandoned and "free" it for others to use)

**Comment by jarun** [comment]
I'm fine with that.

**Comment by jarun** [comment]
Is it possible to keep the name as `imgd` instead of `imgd.py`?

**Comment by reorx** [comment]
Not possible if we want it recognized by setup.py and successfully upload it to pypi, after all it's a Python package, and a package should at least be a .py file. I know it may affect the linux distributing process you've done before, but I think that could be solved by a few lines tweak in the `makedeb` file isn't it?

**Comment by jarun** [comment]
Let me think it over. Given the fact that `imgd` can run as a standalone file, I need to rethink if pypi is really necessary.

**Comment by reorx** [comment]
Up to your choice :) but let me add my suggestions, as we are developing Python code, why not embrace its tool chain and join the community? Besides, being a .py file doesn't mean it couldn't be run standalone, the repo is just the source code, what people use is and should be the packages we delivered.

**Comment by jarun** [comment]
Considering

1. the ease of installation of imgd (single file, single dependency available on all major distros)
2. the fact that I can't maintain the pypi submissions and there's no way to do this from multiple accounts

I have decided not to proceed with the pypi submission. Thanks for your understanding.

**Comment by reorx** [comment]
Hmm, that's OK, I respect your decision.

**Comment by jarun** [comment]
Thank you!

**Comment by jarun** [comment]
@reorx if you are interested, I have my other utility [Buku](https://github.com/jarun/Buku/tree/pypi-packaging) which is indeed a perfect fit for a library and has a dedicated [branch](https://github.com/jarun/Buku/tree/pypi-packaging) for pypi integration. You can have it your way. I will take care of rebasing the latest changes.

**Comment by reorx** [comment]
Looks like buku is already on pypi: https://pypi.python.org/pypi/buku , if it's not you, I think someone has volunteered to make it.

**Comment by jarun** [comment]
Yes, someone started but the full conversion is not complete.
I am linked in the account. I think I can add you. What's your pypi
username?


Regards,

Arun

**Comment by reorx** [comment]
My pypi username is: reorx

But sincerely, I haven't got much time to help recently, I may come back later after finishing the enclosing project I'm working on. Anyway, I'm glad to help when possible.

**Comment by jarun** [comment]
No problem! I'm not in any hurry. I'll add you.
